fix: Properly handle OS updates in Steam
- Output progress of rpm-ostree
- Don't check for an update after installing one
- Stop constantly claiming an update is available

diff --git a/deck/usr/bin/steamos-update b/deck/usr/bin/steamos-update
--- a/deck/usr/bin/steamos-update
+++ b/deck/usr/bin/steamos-update
@@ -1,4 +1,31 @@
-#!/bin/sh
+#!/bin/bash
 
-rpm-ostree update
-exit 0
+# Check if upgrade has already been installed
+if [ -f '/tmp/upgrade-installed' ]; then
+  exit 7 # Upgrade installed
+fi
+
+function upgrade() {
+  rpm-ostree upgrade --unchanged-exit-77
+  echo $? > /tmp/upgrade-check
+}
+UPGRADE=$(upgrade | grep -o '[^ ]*%')
+UPGRADE_CHECK=$(cat /tmp/upgrade-check)
+rm /tmp/upgrade-check
+
+if grep "No upgrade available." <<< ${UPGRADE}; then
+  exit 7 # No upgrade available
+fi
+
+# Check if rpm-ostree failed to update
+if [ ${UPGRADE_CHECK} -eq 77 ]; then
+  exit 0
+fi
+
+# Check if user has gone through initial setup
+if [ -f '~/.local/share/Steam/config/loginusers.vdf' ]; then
+  touch /tmp/upgrade-installed
+  exit 7 # Upgrade installed
+else
+  exit 0 # Upgrade available
+fi
